name: "Composite_Action"

description: "The Composite Action will do some specific tasks"

inputs:

  message:
    description: "Send Message"
    default: "Hello World"
    type: string
    required: true

outputs:
  current_address:
    description: "Get the Living Address"
    value: ${{ steps.address_id.outputs.address }}



runs:
  using: "composite"

  steps:
    - name: "Say Greetings"
      run: "echo ${{ inputs.message }}"
      shell: bash

     - name: "Get Current Address"
       id: address_id
       run: echo "address=200 Manville Hill Road" >> $GITHUB_OUTPUT
       shell: bash