## Create Composite Action.

## The Composite Action cane be created in any folder but the action.yml should exist

name: "Composite_Action"     ### Define name for Composite Action

description: "The Composite Action will do some specific tasks"  ## Define Description for Composite Action

inputs:                                           ## Define Inputs

  message:
    description: "Send Message"
    default: "Hello World"
    type: string
    required: true

outputs:                                            ##  Define Outputs
  current_address:
    description: "Get the Living Address"
    value: ${{ steps.address_id.outputs.address }}

  current_county:
    description: "Get The Current County"
    value: ${{ steps.address_id.outputs.County }}



runs:                                                 ## Defined Key word 
  using: "composite"                                  ## Must be as is

  steps:
    - name: "Say Greetings"
      run: "echo ${{ inputs.message }}"
      shell: bash

    - name: "Get Current Address"
      id: address_id
      run: |
        echo "address=200 Manville Hill Road" >> $GITHUB_OUTPUT
        echo "County=$city" >> $GITHUB_OUTPUT
      shell: bash
      env:
        city: "Cumberland"