##Learning About IF Confition between Jobs

name: if_conition_jobs_wkfw

on: push

jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
          - name: "Running Job1"
            run: echo "Hello Job1   ##On Purpose the Syntax is wrong

    job_2:
        needs: job_1        ##Add Job Dependencies
        runs-on: ubuntu-latest
        steps:
          - name: "Running Job2"
            run: echo "Hello Job2"

    job_3:
        runs-on: ubuntu-latest
        steps:
          - name: "Running Job3"
            id: job3_step1
            run: |
                echo "Hello Job3"
                echo "The Outcome is ${{ steps.job3_step1.outcome }}"

    report_job:
        needs: [job_2,job_3]  ##Add dependcies
        runs-on: ubuntu-latest

      ##Failure Handling   

        if: failure()         
        steps:

            - name: "Repoting Failures"
              run: |
                    echo " One or more Jobs were failed"
                    echo "The Outcome is ${{ steps.job3_step1.outcome }}"






