###Learning Inputs for Workflow_Dispatch Event

name: 4_inputs_wkfw

on: 
  workflow_dispatch:
    inputs:              ##Define Inputs
        name:            ## Input Name
          description: "Enter Your Name"
          required: true
          type: string
          default: Keerthi

jobs:
  input_job:
    runs-on: ubuntu-latest

    steps:
      - name: "Display Your Name"
        run: echo "${{ inputs.name }}"     ## Calling Input.
      
     