name: "Reusable_Articat_Upload_wkfw"

on: 
    workflow_call:
      inputs:
        artifact_name:
            description: "Enter Artifact Name"
            required: false
            default: "Upload Artifacts"
            type: string

jobs:
    artifact_upload_job:

      runs-on: ubuntu-latest
      steps:
        - name: "Create Files"
          run: |
            echo "Hell Jana" > /tmp/buddy.txt
            mkdir -p /tmp/db
            echo "Hello Nana" > /tmp/db/nana.txt
        - name: "Upload Artifacts"
          uses: actions/upload-artifact@v3
          with:
            name: ${{ inputs.artifact_name }}
            path: |
              /tmp/buddy.txt
              /tmp/db/nana.txt
