###A Main Workflow calling a reusable Workflow.

name: Calling_Reusable_wkfw

on: [push,workflow_dispatch]

jobs:
    Get_Repo_Code_Job:
        runs-on: ubuntu-latest
        steps:
            - name: "Get Code from Repo"
              uses: actions/checkout@v3
    
    Calling_reuasble_wkfw_job:
    
      uses: ./.github/workflows/5_reusable_file.yml
      with:
        artifact_name: upload_artifact_1

    Download_Artifacts_Job:
        runs-on: ubuntu-latest
        needs: Calling_reuasble_job
        steps:
            
            - name: "Download Artifacts Jobs"           ##Download Artifacts
              uses: actions/download-artifact@v3
              with:
                name: upload_artifact_1

            - name: "Listing Downloaded Files"    
              run: |
                pwd
                ls -ltr

            - name: "Display Address"                 ##Display Address by using Output of Reusable Workflow Output      
              run: echo " ${{ needs.Calling_reuasble_job.outputs.outcome1 }} "