name: "Calling_Composite_Action_wkfw"

on: push

jobs:

  composite_action_job:    

    runs-on: ubuntu-latest

    steps:
        - name: "Get Code from Repo"
          uses: actions/checkout@v3

        - name: "Calling Composite Action"  
          id: composite_action_id_1
          uses: ./.github/actions
          with:
            message: "Jana Living in Rhodeisland"

        - name: "Get O/p from Composite Action"
          run: echo "The Address is ${{ steps.composite_action_id_1.outputs.current_address }} "